### ISSUE TITLE
Lizard Doggo is missing a "g"!

### ISSUE THREAD

**Issue by TheVisionaryOne** [BuiltBrokenModding/SBM-LizardDoggo#3]
The Lizard Doggo's name is missing a "g", and reads as "Lizard Dogo" instead. I was uncertain, but the fact that this repository is called LizardDogo makes me feel like this might be intentional? As a player (and modpack builder), the mod feels a little unprofessional just because of the typo. I assume you're referring to the internet slang word "doggo."

![2019-11-10_19 27 33](https://user-images.githubusercontent.com/56095032/68559409-c2e4d600-03f1-11ea-83c1-19741ca3c4f8.png)

It's a small bug, but it'd be awesome if you guys could push a quick update to fix it! Absolutely love the mod itself, as well as the other SBM projects you guys do!

**Comment by bl4ckscor3** [comment]
It's not intended. I'll push an update later today.
